# Generated by Django 5.2.11 on 2026-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovidercategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceprovidercategory',
            name='other_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovidercategory',
            name='rent_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
